version: 2
jobs:
  build:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ff:b3:33:e3:ad:97:55:9c:4b:fd:2f:04:cf:ba:8f:8e"
      - checkout
      - run:
          name: Set NODE_NO_WARNINGS variable
          command: export NODE_NO_WARNINGS=1
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t nicolaszelarayan/reciclarg2023:$CIRCLE_SHA1 .
      - run: docker push nicolaszelarayan/reciclarg2023:$CIRCLE_SHA1
      - run: ssh -o StrictHostKeyChecking=no -t -t nicolas_zelarayan@reciclarg.cloud "cd /home/nicolas_zelarayan/React/Reciclarg-React && sudo git pull"
      - run: ssh -o StrictHostKeyChecking=no -t -t nicolas_zelarayan@reciclarg.cloud "cd /home/nicolas_zelarayan/React/Reciclarg-React && sudo docker build -t nicolaszelarayan/reciclarg2023:$CIRCLE_SHA1 -f Dockerfile ."
      - run: ssh -o StrictHostKeyChecking=no -t -t nicolas_zelarayan@reciclarg.cloud "sudo docker stop reciclarg_container || true"
      - run: ssh -o StrictHostKeyChecking=no -t -t nicolas_zelarayan@reciclarg.cloud "sudo docker rm reciclarg_container || true"
      - run: ssh -o StrictHostKeyChecking=no -t -t nicolas_zelarayan@reciclarg.cloud "sudo docker run -p 8082:80 -d --name reciclarg_container nicolaszelarayan/reciclarg2023:$CIRCLE_SHA1"
